openapi: 3.0.3
info:
  title: Individuals Employments
  contact: {}
  version: '2.0'
  description: |
    This API provides individuals' employment information (PAYE only) from HM Revenue and Customs (HMRC). Employment data is only available for tax years commencing 2013-2014.

servers:
  - url: https://api.isc.development.tax.service.gov.uk
    description: Development
  - url: https://api.qa.tax.service.gov.uk
    description: QA
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk
    description: PRD

security:
  - userRestricted:
      - assigned

paths:
  /individuals/employments/:
    get:
      tags:
      - individuals
      summary: Get a list of all available endpoints
      description: Use this endpoint to get a list of available endpoints for Individuals Employments.
      operationId: Getalistofallavailableendpoints
      parameters:
      - name: matchId
        in: query
        description: A short-lived universally unique identifier (UUID), typically valid for several hours. Generated through the Individuals Matching API.
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
      - name: CorrelationId
        in: header
        description: >-
          <p>A UUID, used for traceability purposes.</p>

          <p>Must conform to the regular expression <code class="code--slim">^[0-9a-fA-F]{8}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{12}$</code></p>
        required: true
        style: simple
        schema:
          type: string
          example: 58072660-1df9-4deb-b4ca-cd2d7f96e480
      responses:
        '200':
          description: The resource available to view an individual's employments
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/IndividualsEmploymentsresponse'
                - example:
                    _links:
                      paye:
                        href: /individuals/employments/paye?matchId=57072660-1df9-4aeb-b4ea-cd2d7f96e430{&fromDate,toDate}
                        title: Get an individual's PAYE employment data
                      self:
                        href: /individuals/employments/?matchId=57072660-1df9-4aeb-b4ea-cd2d7f96e430
              example:
                _links:
                  paye:
                    href: /individuals/employments/paye?matchId=57072660-1df9-4aeb-b4ea-cd2d7f96e430{&fromDate,toDate}
                    title: Get an individual's PAYE employment data
                  self:
                    href: /individuals/employments/?matchId=57072660-1df9-4aeb-b4ea-cd2d7f96e430
        '400':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/errorResponse'
                - example:
                    code: INVALID_REQUEST
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        '404':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/errorResponse'
                - example:
                    code: NOT_FOUND
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND
      deprecated: false
  /individuals/employments/paye:
    get:
      tags:
      - individuals
      summary: Get an individual's PAYE employment details
      description: >
        <p>Use this endpoint to get an individual’s PAYE employment details for the requested time period.</p>

        <p>Data is only available for the current and previous 6 tax years.</p>

        <p>The fromDate and toDate are inclusive, so the data returned includes the fromDate and toDate specified.</p>

        <p>You will get a subset of the JSON response shown below based on your assigned scopes.</p>
      operationId: Getanindividual'sPAYEemploymentdetails
      parameters:
      - name: matchId
        in: query
        description: A short-lived universally unique identifier (UUID), typically valid for several hours. Generated through the Individuals Matching API.
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
      - name: fromDate
        in: query
        description: >-
          <p>The date that employments data is requested from.</p>

          Date in the format `YYYY-MM-DD`
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: 2019-01-01
      - name: toDate
        in: query
        description: >-
          <p>The date that employments data is requested to. If missing, it defaults to today's date.</p>

          Date in the format `YYYY-MM-DD`
        style: form
        explode: true
        schema:
          type: string
          example: 2020-03-01
      - name: payeReference
        in: query
        description: "An employer PAYE reference number is a unique identifier a business gets when they register with HMRC as an employer. It must be URL encoded. \n\nAn employer PAYE reference is required for specific API scopes and use cases. Refer to your data requirements to check if you need this."
        style: form
        explode: true
        schema:
          maxLength: 14
          pattern: ^[^ ].{1,14}$
          type: string
          example: 247%2FA1987CB
      - name: CorrelationId
        in: header
        description: >-
          <p>A UUID, used for traceability purposes.</p>

          <p>Must conform to the regular expression <code class="code--slim">^[0-9a-fA-F]{8}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{4}[-][0-9a-fA-F]{12}$</code></p>
        required: true
        style: simple
        schema:
          type: string
          example: 58072660-1df9-4deb-b4ca-cd2d7f96e480
      responses:
        '200':
          description: The individual PAYE employments for the given period
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/IndividualsEmploymentsPayeresponse'
                - example:
                    _links:
                      self:
                        href: /individuals/employments/paye?matchId=57072660-1df9-4aeb-b4ea-cd2d7f96e430&fromDate=2016-02-28&toDate=2017-03-01
                    employments:
                    - startDate: 2019-01-01
                      endDate: 2019-03-31
                      payFrequency: WEEKLY
                      employer:
                        name: ACME Industries Limited
                        payeReference: 247/A1987CB
                        address:
                          line1: Unit 23
                          line2: Utilitarian Industrial Park
                          line3: Utilitown
                          line4: County Durham
                          line5: UK
                          postcode: DH4 4YY
                      payment:
                      - date: 2019-01-31
                        paidTaxablePay: 4765.32
              example:
                _links:
                  self:
                    href: /individuals/employments/paye?matchId=57072660-1df9-4aeb-b4ea-cd2d7f96e430&fromDate=2016-02-28&toDate=2017-03-01
                employments:
                - startDate: 2019-01-01
                  endDate: 2019-03-31
                  payFrequency: WEEKLY
                  employer:
                    name: ACME Industries Limited
                    payeReference: 247/A1987CB
                    address:
                      line1: Unit 23
                      line2: Utilitarian Industrial Park
                      line3: Utilitown
                      line4: County Durham
                      line5: UK
                      postcode: DH4 4YY
                  payment:
                  - date: 2019-01-31
                    paidTaxablePay: 4765.32
        '400':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/errorResponse'
                - example:
                    code: INVALID_REQUEST
              examples:
                BadRequest:
                  description: Invalid request
                  value:
                    code: INVALID_REQUEST
        '404':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/errorResponse'
                - example:
                    code: NOT_FOUND
              examples:
                NotFound:
                  description: Not found
                  value:
                    code: NOT_FOUND
      deprecated: false
components:
  securitySchemes:
    userRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating user restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints for details.
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            assigned: depending on your assigned scopes you will see the json keys your scopes allow.
  schemas:
    errorResponse:
      title: errorResponse
      required:
      - code
      type: object
      properties:
        code:
          type: string
    Address:
      title: Address
      type: object
      properties:
        line1:
          type: string
          description: Address line 1.
          example: Unit 23
        line2:
          type: string
          description: Address line 2.
          example: Utilitarian Industrial Park
        line3:
          type: string
          description: Address line 3.
          example: Utilitown
        line4:
          type: string
          description: Address line 4.
          example: County Durham
        line5:
          type: string
          description: Address line 5.
          example: UK
        postcode:
          type: string
          description: The postcode for the address.
          example: DH4 4YY
      description: The address of the employer.
    Employer:
      title: Employer
      type: object
      properties:
        payeReference:
          type: string
          description: The employer's PAYE reference number. This is a unique identifier that a business gets when they register with HMRC as an employer.
          example: 247/A1987CB
        name:
          type: string
          description: The employer's name.
          example: ACME Industries Limited
        address:
          allOf:
          - $ref: '#/components/schemas/Address'
          - description: The address of the employer.
      description: The employer's details.
    Employment:
      title: Employment
      type: object
      properties:
        payFrequency:
          allOf:
          - $ref: '#/components/schemas/PayFrequency'
          - description: How often the employee is paid.
        startDate:
          type: string
          description: The date the employment started.
          example: 2019-01-01
        endDate:
          type: string
          description: The date the employment ended.
          example: 2019-03-01
        employer:
          allOf:
          - $ref: '#/components/schemas/Employer'
          - description: The employer's details.
        payment:
          type: array
          items:
            $ref: '#/components/schemas/Payment'
          description: The employee's payment details.
    IndividualsEmploymentsPayeresponse:
      title: IndividualsEmploymentsPayeresponse
      required:
      - _links
      - employments
      type: object
      properties:
        _links:
          allOf:
          - $ref: '#/components/schemas/Links1'
          - description: A list of links for possible actions related to this endpoint.
        employments:
          type: array
          items:
            $ref: '#/components/schemas/Employment'
          description: The list of the individual’s PAYE employment data for the requested time period.
      description: Individual's PAYE employments
    IndividualsEmploymentsresponse:
      title: IndividualsEmploymentsresponse
      required:
      - _links
      type: object
      properties:
        _links:
          allOf:
          - $ref: '#/components/schemas/Links'
          - description: A list of links for possible actions related to this endpoint.
      description: Individual's employments
    Links:
      title: Links
      required:
      - paye
      - self
      type: object
      properties:
        paye:
          allOf:
          - $ref: '#/components/schemas/Paye'
          - description: The Uniform Resource Identifier (URI) for the endpoint to get an individual’s PAYE employment data for the requested match ID and time period.
        self:
          allOf:
          - $ref: '#/components/schemas/Self'
          - description: The URL of the endpoint.
      description: A list of links for possible actions related to this endpoint.
    Links1:
      title: Links1
      required:
      - self
      type: object
      properties:
        self:
          allOf:
          - $ref: '#/components/schemas/Self1'
          - description: The Uniform Resource Identifier (URI) for this endpoint.
      description: A list of links for possible actions related to this endpoint.
    Paye:
      title: Paye
      required:
      - href
      type: object
      properties:
        href:
          type: string
          description: The URL of the endpoint.
          example: /individuals/employments/paye?matchId=57072660-1df9-4aeb-b4ea-cd2d7f96e430{&fromDate,toDate}
        title:
          type: string
          description: Get an individual's PAYE employment data
      description: The Uniform Resource Identifier (URI) for the endpoint to get an individual’s PAYE employment data for the requested match ID and time period.
    PayFrequency:
      title: PayFrequency
      enum:
      - WEEKLY
      - FORTNIGHTLY
      - FOUR_WEEKLY
      - CALENDAR_MONTHLY
      - QUARTERLY
      - BI_ANNUALLY
      - ANNUALLY
      - ONE_OFF
      - IRREGULAR
      type: string
      description: How often the employee is paid.
    Payment:
      title: Payment
      type: object
      properties:
        date:
          type: string
          description: The date of the payment.
          example: 2019-01-31
        paidTaxablePay:
          type: number
          description: The amount the employee was paid.
          example: 4765.32
    Self:
      title: Self
      required:
      - href
      type: object
      properties:
        href:
          type: string
          example: /individuals/employments/?matchId=57072660-1df9-4aeb-b4ea-cd2d7f96e430
      description: The URL of the endpoint.
    Self1:
      title: Self1
      required:
      - href
      type: object
      properties:
        href:
          type: string
          description: The URL of the endpoint.
          example: /individuals/employments/paye?matchId=57072660-1df9-4aeb-b4ea-cd2d7f96e430&fromDate=2016-02-28&toDate=2017-03-01
      description: The Uniform Resource Identifier (URI) for this endpoint.
tags:
- name: individuals
  description: ''
