#%RAML 1.0
---

title: Individuals Employments
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
     content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
 - title: Testing
   content: !include docs/testing.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/:
  get:
    displayName: Entry point
    description: This is the entry point to the API and returns one or more links.
    is: [headers.acceptHeader]
    (annotations.sandboxData): !include sandbox/root.md
    (annotations.scope): "read:individuals-employments"
    securedBy: [ sec.oauth_2_0: { scopes: [ "read:individuals-employments" ] } ]
    responses:
      200:
        description: The resource available to view an individual's employments
        body:
          application/json:
            example: !include examples/root.json
            type: !include schemas/root.json

/hello-world:
  get:
    displayName: Hello world endpoint
    description: This is a hello world enpoint
    responses:
      200:
        body:
          text/plain:
            example: Hello world
